### PR TITLE
Magic.hs: Fix for machines without MEM_UNALIGNED_OPS  and base >= 4.17

### PR DESCRIPTION
**Pull request by kubek2k**

### CODE REVIEW

**Comment by centromere** [comment]
@parsonsmatt Would you be willing to review and merge this if appropriate?

**Comment by parsonsmatt** [comment]
I'm not a maintainer for this package

**Comment by kubek2k** [comment]
Looks like it's rather @bgamari - could you have a look?

**Comment by brprice** [comment]
FTR, my understanding is that this is only necessary for arches without `MEM_UNALIGNED_OPS`, i.e. anything other than `i386` and `x86_64` (and potentially for ghc<7.10) (in particular, `aarch64`/apple silicon). In particular, for x86_64, cborg-0.2.8.0 builds fine with ghc-9.4.3 -- I believe the cpp means that the definition on [Magic.hs:171](https://github.com/well-typed/cborg/blob/master/cborg/src/Codec/CBOR/Magic.hs#L171) is in effect. But it does fail to build on `aarch64-darwin`.

Perhaps to avoid confusion in the future the PR title and commit message could be updated to reflect this?

**Comment by gelisam** [comment]
I independently came up with a [mostly-identical patch](https://github.com/well-typed/cborg/issues/311#issuecomment-1508989466), so I also think that this is the correct fix.

**Comment by Bodigrim** [comment]
@FinleyMcIlwaine could this please be merged? Otherwise `cborg` does not work on M1 machines.

**Comment by unorsk** [comment]
Having this problem on M2 too.

**Comment by nicolashery** [comment]
We also had this problem building on Apple Silicon. Confirm that this PR fixed it. Looking forward to seeing it merged!

**Pull request merged**
