### PR TITLE
Updates for GHC 8.10

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by sjakobi** [comment]
The `serialise` benchmarks don't build with 8.10 yet. https://github.com/DanielSchuessler/th-expand-syns/pull/16 should probably fix that.

**Comment by sjakobi** [comment]
Benchmarks are now disabled in CI for GHC 8.10 due to fpco/th-utilities#9.

**Comment by sjakobi** [comment]
@thoughtpolice, @dcoutts, @bgamari: This should be ready to go.

**Comment by sjakobi** [comment]
Ping @thoughtpolice, @dcoutts, @bgamari! :)

If you can't find the time to review, please consider giving me permission to take care of compatibility issues like this one myself! :) (We had discussed this before in https://github.com/well-typed/cborg/issues/215#issuecomment-569561706)

**Comment by bgamari** [comment]
Sorry for the delay, @sjakobi! Merged. I'll try to put out a release shortly.

**Pull request merged**
